export function createElements() {
  return {
    body: document.body,
    trafficLight: document.getElementById("trafficLight"),
    brandName: document.getElementById("brandName"),
    versionBtn: document.getElementById("versionBtn"),
    stateText: document.getElementById("stateText"),
    modeBtn: document.getElementById("modeBtn"),
    settingsBtn: document.getElementById("settingsBtn"),
    pinBtn: document.getElementById("pinBtn"),
    refreshBtn: document.getElementById("refreshBtn"),
    themeSwitchBtn: document.getElementById("themeSwitchBtn"),
    minimizeBtn: document.getElementById("minimizeBtn"),
    closeBtn: document.getElementById("closeBtn"),
    meterHost: document.getElementById("meterHost"),
    dockBarHost: document.getElementById("dockBarHost"),
    dockBarFill: document.getElementById("dockBarFill"),
    dataBarCards: Array.from(document.querySelectorAll("[data-data-bar-slot]")),
    statusDot: document.getElementById("statusDot"),
    statusIcon: document.getElementById("statusIcon"),
    statusText: document.getElementById("statusText"),
    widget: document.querySelector(".widget"),
    onboardingOverlay: document.getElementById("onboardingOverlay"),
    onboardingTitle: document.getElementById("onboardingTitle"),
    onboardingDescription: document.getElementById("onboardingDescription"),
    onboardingPrevBtn: document.getElementById("onboardingPrevBtn"),
    onboardingNextBtn: document.getElementById("onboardingNextBtn"),
    onboardingStepDots: Array.from(
      document.querySelectorAll("[data-onboarding-step-dot]"),
    ),
    onboardingCloseBtn: document.getElementById("onboardingCloseBtn"),
    settingsPanel: document.getElementById("settingsPanel"),
    settingsTitle: document.getElementById("settingsTitle"),
    settingsCloseBtn: document.getElementById("settingsCloseBtn"),
    codexPathLabel: document.getElementById("codexPathLabel"),
    codexPathInput: document.getElementById("codexPathInput"),
    chooseCodexBtn: document.getElementById("chooseCodexBtn"),
    autoUpdateLabel: document.getElementById("autoUpdateLabel"),
    autoUpdateHint: document.getElementById("autoUpdateHint"),
    autoUpdateSwitch: document.getElementById("autoUpdateSwitch"),
    autoStartLabel: document.getElementById("autoStartLabel"),
    autoStartHint: document.getElementById("autoStartHint"),
    autoStartSwitch: document.getElementById("autoStartSwitch"),
    hideDockIconRow: document.getElementById("hideDockIconRow"),
    hideDockIconLabel: document.getElementById("hideDockIconLabel"),
    hideDockIconHint: document.getElementById("hideDockIconHint"),
    hideDockIconSwitch: document.getElementById("hideDockIconSwitch"),
    updateProxyLabel: document.getElementById("updateProxyLabel"),
    updateProxyInput: document.getElementById("updateProxyInput"),
    updateProxyHint: document.getElementById("updateProxyHint"),
    refreshIntervalLabel: document.getElementById("refreshIntervalLabel"),
    refreshIntervalInput: document.getElementById("refreshIntervalInput"),
    themeLabel: document.getElementById("themeLabel"),
    themeSelect: document.getElementById("themeSelect"),
    languageLabel: document.getElementById("languageLabel"),
    localeSelect: document.getElementById("localeSelect"),
    meterWindowLabel: document.getElementById("meterWindowLabel"),
    meterWindowSelect: document.getElementById("meterWindowSelect"),
    ballSizeLabel: document.getElementById("ballSizeLabel"),
    ballSizeSelect: document.getElementById("ballSizeSelect"),
    ballSnapStyleLabel: document.getElementById("ballSnapStyleLabel"),
    ballSnapStyleSelect: document.getElementById("ballSnapStyleSelect"),
    dataBarLabels: [
      document.getElementById("dataBar1Label"),
      document.getElementById("dataBar2Label"),
      document.getElementById("dataBar3Label"),
    ],
    dataBarSelects: [
      document.getElementById("dataBar1Select"),
      document.getElementById("dataBar2Select"),
      document.getElementById("dataBar3Select"),
    ],
    logLevelLabel: document.getElementById("logLevelLabel"),
    logLevelSelect: document.getElementById("logLevelSelect"),
    customSelectShells: Array.from(
      document.querySelectorAll(".custom-select-shell"),
    ),
    settingsError: document.getElementById("settingsError"),
    cancelSettingsBtn: document.getElementById("cancelSettingsBtn"),
    saveSettingsBtn: document.getElementById("saveSettingsBtn"),
    saveSettingsText: document.getElementById("saveSettingsText"),
    sourcePickerShell: document.getElementById("sourcePickerShell"),
    sourcePickerBtn: document.getElementById("sourcePickerBtn"),
    sourcePickerLabel: document.getElementById("sourcePickerLabel"),
    sourcePickerMenu: document.getElementById("sourcePickerMenu"),
    tabBasicBtn: document.getElementById("tabBasicBtn"),
    tabSourcesBtn: document.getElementById("tabSourcesBtn"),
    tabSystemBtn: document.getElementById("tabSystemBtn"),
    basicSettingsScroll: document.getElementById("basicSettingsScroll"),
    sourcesSettingsScroll: document.getElementById("sourcesSettingsScroll"),
    systemSettingsScroll: document.getElementById("systemSettingsScroll"),
    sourcesContainer: document.getElementById("sourcesContainer"),
    ballContextMenu: document.getElementById("ballContextMenu"),
    activeSourceIndicator: document.getElementById("activeSourceIndicator"),
  };
}
